include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - lib/models/*.dart
    - lib/**/*.graphql.dart
    - lib/**/*.g.dart
    - ios/.symlinks
    #  enable-experiment:
    #  - nonfunction-type-aliases
  errors:
    undefined_prefixed_name: ignore
